### ISSUE TITLE
How to interpret the results of the TIPs genotyping

### ISSUE THREAD

**Issue by dtx282000** [cgroza/GraffiTE#21]
Hi,

I was lucky to have the TIPs genotyping results after running the GraffiTE code. My results are as follows:

<img width="1094" alt="image" src="https://github.com/cgroza/GraffiTE/assets/24269804/526a4408-0185-4515-a9a6-42557bfafde1">

Some questions are as follows:
1. What does the dot in the ID column in the Figure mean? Additionally, I have checked the ID. I found that the ID was not in the pangenome.vcf file generated by the previous step.
2. In the INFO column, the ID with the dot has any TE annotations. How can we solve it?
3. I would like to perform the gene annotation for the TIPs genotyping file (vcf.) based on the reference genone gtf file. Do you have any recommendations on how to do that?

 Looking forward to hearing from you！

**Comment by clemgoub** [comment]
Hello there!

Could you tell us which VCF is it? If it comes from the folder `1_SV_Search` then there will be no TE annotation, and this file only contains the raw insertions and deletions found relative to the reference genome.

1. The ID is the original name given by the SV caller to the variant, here `svim-asm` is the caller. The name is taken from the first genome this variant is encountered, but it may as well be present in other samples. You can know this using the `SUPP_VEC` field in `3_TSD_Search/pangenome.vcf`; a description is of each field is available [here](https://github.com/cgroza/GraffiTE?tab=readme-ov-file#output-vcfs).

2. If there is no TE annotation, it is likely this VCF is from the first step. For presence/absence, you will find TE annotations in the the folder `3_TSD_Search/pangenome.vcf`; if you used reads to genotype further these presence/absence, then you'll find the final genotypes in `4_Genotyping/GraffiTE.merged.genotypes.vcf`

3. My suggestion would be to convert the GraffiTE VCF into a gff or bed (bed is easier). It is very easy to do so with 
```
grep -v '#' 3_TSD_search/pangenome.vcf | awk '/INS/ {print $1"\t"$2"\t"($2+1)"\t"$3; next} /DEL/ {print $1"\t"$2"\t"$2+length($4)"\t"$3}' > TIP_coordinates.bed
```
Then, you can convert your gtf to bed as well, maybe with a tool like [this one](https://gffutils.readthedocs.io/en/latest/gtf2bed.html#:~:text=gtf2bed%20converts%20the%20contents%20of,entry%20in%20the%20input%20GTF.)
Finally, use [bedtools intersect](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html) to check the location of the TIP relative to the genes annotations. You can also add flanking of the size you like to the TIP_coordinates.bed using [bedtools window](https://bedtools.readthedocs.io/en/latest/content/tools/window.html). Let me know if this is working for you, otherwise, please let me know what you would exactly like as output an I can help!

Cheers,

Clément

**Comment by dtx282000** [comment]
Hi, Dr.Clément

This vcf file from the last step (4_Genotyping).

<img width="1011" alt="image" src="https://github.com/cgroza/GraffiTE/assets/24269804/2e9febd7-1b41-4ad2-820a-26512191dd52">

regards！

Deng

**Comment by clemgoub** [comment]
Hello Deng,

You actually have 176188 likely pME genotyped in total, not 81724. It is because not all ID names keep the "svim_asm" suffix and sometimes SURVIVOR (the tool that merge the variants across samples) will replace the ID name to something less meaningful. It is a little bit unpredictable, so I would simply rely on the TE annotation given in the INFO field regardless of the variant name. The ID is just a unique locus identifier, the name is not very relevant.

This is expected to "loose" some variants at genotyping (between step 3 and 4), especially if you used short-reads for genotyping.

To filter further your results, I encourage you to analyse the INFO field. If you have an idea of which family should be mobile and their expected size, it can help remove false positives. If you don't really know what to expect, a conservative filter could be to filter for 'n_hits=1' (grep `n_hits=1;`) ; meaning that only 1 TE hit is present in the variant (1 family). However, sometimes real TE insertions can generate more than 1 hit, so I recommend users to have some manual checking of the outputs before interpreting the results. 

Cheers,

Clément

**Comment by dtx282000** [comment]
Hello, Dr. Clément,

Thank you for your response. Now, I understand these questions.
